### ISSUE TITLE
Permission to backport headers and NIDS to VitaSDK as MIT

### ISSUE THREAD

**Issue by frangarcj** [DolceSDK/headers#10]
In order to not have problems with GPL poisoning, VitaSDK requires re-licensing the code to the MIT license from GPLv3. 
Hopefully, if it is okay with you all DolceSDK contributors, we just need a statement with your permission to the code being re-licensed. Full credit will be given to all the headers and NIDs.

The main goal is to have a close collaboration between both projects in a respectful way with the contributions of each of them.

Thanks for your work and I hope to hear from you soon.

**Comment by cuevavirus** [comment]
You have the wrong attitude for someone asking me for a favour.
