### ISSUE TITLE
Verification of library and function location in NIDs DB

### ISSUE THREAD

**Issue by cuevavirus** [DolceSDK/headers#2]
By using a reference NIDs DB generated from modules, verify that libraries belong to the correct module and functions belong to the correct library.

**Comment by cuevavirus** [comment]
Done

https://github.com/DolceSDK/headers/commit/429b518467056dab29acfab6d99b71849568dde5
https://github.com/DolceSDK/headers/commit/e78f9d26acd84f4c64656d8366c065ab661a9d5c
https://github.com/DolceSDK/headers/commit/744dcc0ca6254dffaa3bea04a9e486a990f17582
https://github.com/DolceSDK/headers/commit/90727850082dd0550ce2e2bf2234de91dc3cf397
https://github.com/DolceSDK/headers/commit/b646ac777c35ae3a4d27ecad7bb4567f64c4d8a8

**Comment by bythos14** [comment]
I see this is what you were referring to.

**Comment by bythos14** [comment]
Quick question, if you don't mind answering. How were the libraries functional when they were placed in the module, wouldn't the wrong module NID affect things? Or is dynamic linking on the vita only dependent on the module and function NIDs?

**Comment by cuevavirus** [comment]
The module NID is in fact called the debug fingerprint, and not truly a NID. It is not relevant in dynamic linking.

**Comment by bythos14** [comment]
Ah, good to know. Thanks for the info.
